#!/usr/bin/env bash
#install nginx 
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod a+rwx /var/www/html/index.nginx-debian.html
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
