#!/usr/bin/env bash
#install nginx 
#!/usr/bin/env bash
#install nginx 
apt-get -y update
apt-get -y install nginx
sed -i '0,/listen .*/s//listen 80 default_server;/' /etc/nginx/sites-available/default
sudo echo 'Holberton School for the win!' | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart

