#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://www.linkedin.com/in/loubaris-ziyad-a3798320a;\n\t}\n"
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default
sudo service nginx start