#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'

apt-get -y update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/ERROR404.html
sed -i "25i /server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}" /etc/nginx/sites-available/default
service nginx start