#!/usr/bin/env bash
#install nginx 
MYGITHUB="\\\tlocation /redirect_me {\n\t\t return 301 https://github.com/ziyadloubaris;\n\t}\n"

apt-get -y update
apt-get -y install nginx
sed -i '0,/listen .*/s//listen 80 default_server;/' /etc/nginx/sites-available/default
sudo sed -i "30i $MYGITHUB" /etc/nginx/sites-available/default 
sudo echo 'Holberton School for the win!' | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/ERROR404.html
sed -i "25i /server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}" /etc/nginx/sites-available/default
service nginx restart

